server-name: "lobby"
lobby-server-name: "lobby"
api-enabled-servers:
  - "lobby"
  - "rpg"
  - "island"
  - "collect"
database:
  host: "localhost"
  port: 3306
  name: "content_db_replica"
  user: "root"
  password: ""